### ISSUE TITLE
errorauthunknownstate - Empty state for B2C users with both AB2C and social identities

### ISSUE THREAD

**Issue by thebenkahn** [GopalSharma/auth_azureb2c#33]
Good day, using AzureB2C auth. We are allowing users to register an account directly on AzureB2C, or login with social logins. It works perfectly fine for users that sign in for the for the first time using either method. However if a user utilizes a second method they are not able to login successfully.

For example, if I first create an account directly on AzureB2C using the email example.user@gmail.com I can login.
If I log out, and then the next time use the Google social login button to login to B2C, I get the error below:

Vice versa, if I use a social login the first time I login, then on a second visit register a local AzureB2C account with the same email address, the error occurs.

```
Debug info:
Error code: errorauthunknownstate×Dismiss this notification
Stack trace:
line 206 of /auth/azureb2c/classes/loginflow/authcode.php: moodle_exception thrown
line 107 of /auth/azureb2c/classes/loginflow/authcode.php: call to auth_azureb2c\loginflow\authcode->handleauthresponse()
line 105 of /auth/azureb2c/auth.php: call to auth_azureb2c\loginflow\authcode->handleredirect()
line 29 of /auth/azureb2c/index.php: call to auth_plugin_azureb2c->handleredirect()
```
We also frequently see a blank white screen with the text "ERROR1" if a user attempts additional logins after the initial exception.

In Azure B2C I understand there is one user object, but that each user with multiple login methods to B2C will have multiple "identities" and that the sub claim passed with the login token is different depending on which identity is used.

Does this plugin support using both social login and local B2C identities? If so, can you possibly provide some feedback on how this needs to be addressed in the AzureB2C configuration?

**Comment by thebenkahn** [comment]
Greetings again, to provide further context, here are the (sanitized) claims passed for a local and social identity for the same user.

```
Local Account:
{ "alg": "RS256", "kid": "X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk", "typ": "JWT" }.
{ "ver": "1.0", "iss": "https://example.b2clogin.com/af2fff1c-72a2-4ba4-80a2-e4decbb13b03/v2.0/", "sub": "ee9684bd-6efb-4a25-b219-33d7f1de1401", "aud": "c6261b2d-bcfb-4181-b458-70874eb7676a", "exp": 1706519086, "nonce": "defaultNonce", "iat": 1706515486, "auth_time": 1706515486, "oid": "ee9684bd-6efb-4a25-b219-33d7f1de1401", "given_name": "example", "family_name": "User", "extension_Origin": "LMS", "name": "example User", "emails": [ "user.example@gmail.com" ], "tfp": "B2C_1_SignUpAndSignIn", "nbf": 1706515486 }

Social Account:
 { "alg": "RS256", "kid": "X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk", "typ": "JWT" }.
 { "ver": "1.0", "iss": "https://example.b2clogin.com/af2fff1c-72a2-4ba4-80a2-e4decbb13b03/v2.0/", "sub": "7e768719-c0cd-4780-8b6d-77fb0b66976e", "aud": "c6261b2d-bcfb-4181-b458-70874eb7676a", "exp": 1706519275, "nonce": "defaultNonce", "iat": 1706515675, "auth_time": 1706515675, "given_name": "example", "family_name": "User", "name": "example User", "idp": "google.com", "oid": "7e768719-c0cd-4780-8b6d-77fb0b66976e", "emails": [ "user.example@gmail.com" ], "extension_Origin": "LMS", "tfp": "B2C_1_SignUpAndSignIn", "nbf": 1706515675 }
```

**Comment by danielavetica** [comment]
Hello,

I also see a blank screen with just the text "ERROR1"... no further details on where to find this issue..
Can someone help me (promptly) where to find this issue?

**Comment by danielavetica** [comment]
got it! 

its testing state in /classes/login/authcode.php on line 437..
it's not in the GIT, but it's in the ZIP you can download from moodle.org ;) 

please update the moodle.org plugin!!

**Comment by GopalSharma** [comment]
@danielavetica Thank you for putting your valuable comments to help other users out.
I'm occupied with a lot of other work, I will make the changes soon.
